data:
  batch_size: 2
  data_dir: "/home/paperspace/dlmusic/hw3/src/data/Pop1K7/midi_analyzed"
  num_workers: 2
  max_seq_len: 256
  overlap: 64
  train_val_split: 0.9

model:
  d_model: 256
  n_head: 4
  n_layers: 4
  d_ff: 1024
  dropout: 0.1
  mem_len: 256

training:
  epochs: 100
  gradient_accumulation_steps: 4
  eval_every_n_steps: 500
  fp16: true
  gradient_clip_val: 1.0
  learning_rate: 0.0001
  log_every_n_steps: 100
  save_every_n_steps: 1000
  warmup_steps: 100
  use_gradient_checkpointing: true  # For large models
  max_steps: 10000
  save_every: 1000
  eval_every: 500
  max_grad_norm: 1.0
  weight_decay: 0.01
  pin_memory: true
  val_batch_size: 2

generation:
  max_length: 2048
  num_samples: 20
  temperatures:
    - 0.8
    - 1.0
    - 1.2
  top_k:
    - 20
    - 40
    - 60
